name:                lucca-picross
version:             0.1.0.0
github:              "robotbrain/lucca-picross"
license:             EPL
author:              "Elise Sieberer"
maintainer:          ""
copyright:           "2019 Elise Sieberer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lucca-picross#readme>

dependencies:
- base >= 4.7 && < 5
  
executables:
  lucca-picross:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vector
    - matrix
